### ISSUE TITLE
why do you use a activity context for Toast? 

### ISSUE THREAD

**Issue by hss01248** [drakeet/ToastCompat#1]
just use a Application context ,and BadTokenException never happens.
 here is the best prectice for toast 
https://github.com/hss01248/Toasty

**Comment by drakeet** [comment]
This exception occurs regardless of whether the Context you passed to Toast is an Activity or ApplicationContext or Service. And you can not try-catch it. Almost helpless.

**Comment by drakeet** [comment]
https://github.com/drakeet/ToastCompat/blob/master/README.md#why

**Comment by drakeet** [comment]
在 Android Toast 源码中，关于最终使用的 `Context` 是这样的：

```java
Context context = mView.getContext().getApplicationContext(); // !!
String packageName = mView.getContext().getOpPackageName();
if (context == null) {
    context = mView.getContext();
}
mWM = (WindowManager)context.getSystemService(Context.WINDOW_SERVICE);
```

所以无论你传递给 Toast 的是什么 Context，都将导致一样结果：

> This exception occurs regardless of whether the Context you passed to Toast is an Activity or ApplicationContext or Service. And you can not try-catch it. Almost helpless.

另外，我们真机真实实验证明，即使传递 Application Context 和 Service Context，也确实都是这样的结果，即在小概率情况下将导致 crash。

再者，就算是 Application Context 能够修复这个问题，这也是不应该的，Toast 提高的方法参数本来就接受的是 Context 而没有任何说明需要使用 Application Context，如果有必要的话，官方会在内部使用 Application Context，要求只能使用 Application Context 是一件麻烦而且没有必要的事情，即使有效，也是不应该的。而实际上，这么做无效。

最后，这个项目是一个 Toast 兼容库，而不是 Toast 拓展库，Toast 本来就不需要什么拓展或者难以使用，哪里需要什么 best practice...
