### ISSUE TITLE
Is Log.e better than Log.i ?

### ISSUE THREAD

**Issue by Rogero0o** [drakeet/ToastCompat#2]
`try {
                Log.d(TAG, "WindowManager's addView(view, params) has been hooked.");
                base.addView(view, params);
            } catch (BadTokenException e) {
                Log.i(TAG, e.getMessage());
                if (badTokenListener != null) {
                    badTokenListener.onBadTokenCaught(toast);
                }
            }
`
I found this in SafeToastContext.java , but is that Log.e better than Log.i ?
Not a big deal, but make me feel better. 
Or you have other purposes about this? PLZ let me know, Thanks

**Comment by drakeet** [comment]
The exception is known and caught now, so it should not log a error but information.

**Comment by drakeet** [comment]
If you would improve it to be a error log you could use the listener to log by yourself. 
The use of error usually indicates that this exception is unexpected, but it is clear that this exception is now known to us.

**Comment by drakeet** [comment]
Errors can cause panic. Since we've already held it, we should not use it.
