### ISSUE TITLE
Some device could not show Toast

### ISSUE THREAD

**Issue by cat9** [drakeet/ToastCompat#5]
Hi,
i use your library for my project, i think it is a good way to solve the problem.

but i test in the phone (NUBIA Z17S  android7.1.1), it could not show the toast.
there is no any useful message for debug.
i think some system use the (xxx instanceof WindowManagerImpl) to avoid
any hack from outside of system.

Those solution has some bug in some device: It do not show the toast in some device.
if somebody have to use these solution,it should make sure these code just use in android7.1.1

sorry for my poor english.

**Comment by drakeet** [comment]
Thank you for your feedback.

You have no evidence to explain your guess. And there's no reason for the system to do that.

Please carry out a controlled experiment.

BTW: Do you disable the application notification, because Toast is linked to the notification.

**Comment by drakeet** [comment]
Checking `xxx instanceof WindowManagerImpl` is no any help for stopping hacks, so the system doesn't do it at all and it's a nonsense to do it.

**Comment by cat9** [comment]
i think your solution is great too,but  the toast could not be shown on the phone(NUBIA Z17S).
[i can see these logs at logcat](https://github.com/drakeet/ToastCompat/blob/2e935428b96b20e2173ca362659b2f4c655e6ab5/library/src/main/java/me/drakeet/support/toast/SafeToastContext.java#L85)

but i change the code back to Toast from ToastCompat, i can see the toast again.
It is weird，but it do happen.

**Comment by drakeet** [comment]
Thanks! I will try to test it but I don't have a NUBIA Z17S device. If you could find something wrong and create PR it would be great.

**Comment by drakeet** [comment]
I just run the sample on an Android **7.1.1** emulator, it works.

**Comment by cat9** [comment]
i run on my (moto z play android 7.1.1),it works too.
but i don't know how much device have the same issue. and i can't find any key point to detect these problem. so it has a risk for me to use in my project.
if you have any idea about it, feel free to contact me,and i will try it on NUBIA Z17S.

**Comment by drakeet** [comment]
Which ROM are you using?

**Comment by cat9** [comment]
哈哈，才发现你是中国人。
是我同事的手机，NUBIA的手机，好像刚上市不久，不知是他们的rom改了什么。我今天做了很多尝试，都没找到问题所在。

**Comment by drakeet** [comment]
是的，你可以留意下完整日志，或者将我那 try catch 去掉，看看会不会 crash 或者报什么错。感谢你的反馈和帮助！我之后也去找一下这机子试试。

**Comment by cat9** [comment]
catch后面的日志是没打印出来的。代码是调用成功了，可是没显示出来

**Comment by cat9** [comment]
public Object getSystemService(@NonNull String name) {
            if (Context.WINDOW_SERVICE.equals(name)) {
                // noinspection ConstantConditions
                return new WindowManagerWrapper((WindowManager) getBaseContext().getSystemService(name));
            }
            return super.getSystemService(name);
        }

这里如果注释掉上面的代码，直接return super.getSystemService(name)， 在NUBIA Z17S就能显示Toast了，这里说明在这个rom的WindowManager具有防替代的实现

**Comment by drakeet** [comment]
不是防替代（Toast 没有必要 hack，要不是修复系统 bug，谁会去 hack Toast 呀），而是可能这个 ROM 使用了瞎改的 WindowManager，很可能是因为 NUBIA 获取 Toast WindowManager 的 SystemService name 不是 `Context.WINDOW_SERVICE`，你可以打印一下这个 name，看看正常结果之下，name 是什么，如果确定是另外的 name，就可以做兼容了。

**Comment by drakeet** [comment]
没有系统源码，不知道 NUBIA 瞎改了什么。Toast 有什么可防的，它的内容价值很低，而且如果没有 root，应用也只能自己 hack 自己的 Toast。这些国产系统真是各种不按套路出牌。

**Comment by drakeet** [comment]
你可以在 ApplicationContextWrapper#getSystemService 那拿取并打印一下正常结果之下的 WindowManager 对象看看，使用如下代码：
```java
@Override
public Object getSystemService(@NonNull String name) {
    if (Context.WINDOW_SERVICE.equals(name)) {
        Object object = super.getSystemService(name);
        Log.d(TAG, "[getSystemService]-->" + object.getClass().getName());
        return object;
    }
    return super.getSystemService(name);
}
```
正常情况下，它应该是 `android.view.WindowManagerImpl`，看看 NUBIA 是不是替换了这个类。

谢谢！

**Comment by cat9** [comment]
我debug看过了，nubia还是这个类android.view.WindowManagerImpl。

**Comment by cat9** [comment]
Hi,
我无法在你这个方法的基础上修复我在Nubia遇到的问题，从而使我必须用另外方法捕获了BadTokenException这个错误，我新建了一个repo而且使用了和你这个项目同一个名称[ToastCompat](https://github.com/cat9/ToastCompat)，希望能帮到后来者，请你不要介意。你可以去查看一下，希望对你有点帮助，同时感谢你的指导。你可以关闭这个问题或者留着，希望只有nubia z17s出现这个问题。

**Comment by drakeet** [comment]
可以的👍，不客气。这个 issue 可以留着，如果了解 Nubia 改了什么，未来我可能修复它。

**Comment by threeloe** [comment]
你们两个国人真逗

**Comment by liverloop** [comment]
This is too funny...

**Comment by captain-miao** [comment]
ToastCompat 有些 MIUI 10手机(不是所有) 也不弹 Toast，开启了悬浮窗权限，跟这个现象一样。

// 我也没有 MIUI 10 的手机重现，所以也暂时指定了 API 27 才 hook。

**Comment by drakeet** [comment]
@captain-miao I decided to modify this project so that it only works on Android 7.1.
