### ISSUE TITLE
toast不显示

### ISSUE THREAD

**Issue by fade0706** [drakeet/ToastCompat#6]
你好在引入ToastCompat后今早在同事的手机上发现Toast不显示，手机型号如下
Redmi Note 3
MIUI 9.2
android 5.0.2

**Comment by fade0706** [comment]
把手机悬浮窗权限打开后可以正常显示，但是原生Toast本身是不需要悬浮窗权限

**Comment by drakeet** [comment]
与 #5 重复，见 #5 。
